import { isKnownPlaceholderCode } from "@/lib/documents/placeholder-aliases";

export type PlaceholderDefinition = {
  code: string;
  group:
    | "company"
    | "client"
    | "customer"
    | "vehicle"
    | "order"
    | "employee"
    | "document"
    | "deal"
    | "vehicle_a"
    | "vehicle_b"
    | "payment"
    | "registration"
    | "service"
    | "handover"
    | "power_of_attorney";
  labelKey: string;
  exampleKey: string;
};

export const DOCUMENT_TEMPLATE_PLACEHOLDERS: PlaceholderDefinition[] = [
  { code: "{{company.name}}", group: "company", labelKey: "phCompanyName", exampleKey: "exCompanyName" },
  { code: "{{company.ico}}", group: "company", labelKey: "phCompanyIco", exampleKey: "exCompanyIco" },
  { code: "{{company.dic}}", group: "company", labelKey: "phCompanyDic", exampleKey: "exCompanyDic" },
  { code: "{{company.address}}", group: "company", labelKey: "phCompanyAddress", exampleKey: "exCompanyAddress" },
  { code: "{{company.city}}", group: "company", labelKey: "phCompanyCity", exampleKey: "exCompanyCity" },
  { code: "{{company.phone}}", group: "company", labelKey: "phCompanyPhone", exampleKey: "exCompanyPhone" },
  { code: "{{company.email}}", group: "company", labelKey: "phCompanyEmail", exampleKey: "exCompanyEmail" },
  { code: "{{company.bank_account}}", group: "company", labelKey: "phCompanyBankAccount", exampleKey: "exCompanyBankAccount" },
  { code: "{{company.representative}}", group: "company", labelKey: "phCompanyRepresentative", exampleKey: "exCompanyRepresentative" },
  { code: "{{customer.full_name}}", group: "customer", labelKey: "phCustomerFullName", exampleKey: "exCustomerFullName" },
  { code: "{{customer.address}}", group: "customer", labelKey: "phCustomerAddress", exampleKey: "exCustomerAddress" },
  { code: "{{customer.bank_account}}", group: "customer", labelKey: "phCustomerBankAccount", exampleKey: "exCustomerBankAccount" },
  { code: "{{customer.birth_date_or_ico}}", group: "customer", labelKey: "phCustomerBirthDateOrIco", exampleKey: "exCustomerBirthDateOrIco" },
  { code: "{{customer.document_number}}", group: "customer", labelKey: "phCustomerDocumentNumber", exampleKey: "exCustomerDocumentNumber" },
  { code: "{{customer.email}}", group: "customer", labelKey: "phCustomerEmail", exampleKey: "exCustomerEmail" },
  { code: "{{customer.phone}}", group: "customer", labelKey: "phCustomerPhone", exampleKey: "exCustomerPhone" },
  { code: "{{client.full_name}}", group: "client", labelKey: "phClientFullName", exampleKey: "exClientFullName" },
  { code: "{{client.company_name}}", group: "client", labelKey: "phClientCompanyName", exampleKey: "exClientCompanyName" },
  { code: "{{client.birth_date}}", group: "client", labelKey: "phClientBirthDate", exampleKey: "exClientBirthDate" },
  { code: "{{client.id_number}}", group: "client", labelKey: "phClientIdNumber", exampleKey: "exClientIdNumber" },
  { code: "{{client.address}}", group: "client", labelKey: "phClientAddress", exampleKey: "exClientAddress" },
  { code: "{{client.phone}}", group: "client", labelKey: "phClientPhone", exampleKey: "exClientPhone" },
  { code: "{{client.email}}", group: "client", labelKey: "phClientEmail", exampleKey: "exClientEmail" },
  { code: "{{vehicle.make}}", group: "vehicle", labelKey: "phVehicleMake", exampleKey: "exVehicleMake" },
  { code: "{{vehicle.model}}", group: "vehicle", labelKey: "phVehicleModel", exampleKey: "exVehicleModel" },
  { code: "{{vehicle.year}}", group: "vehicle", labelKey: "phVehicleYear", exampleKey: "exVehicleYear" },
  { code: "{{vehicle.vin}}", group: "vehicle", labelKey: "phVehicleVin", exampleKey: "exVehicleVin" },
  { code: "{{vehicle.plate}}", group: "vehicle", labelKey: "phVehiclePlate", exampleKey: "exVehiclePlate" },
  { code: "{{vehicle.mileage}}", group: "vehicle", labelKey: "phVehicleMileage", exampleKey: "exVehicleMileage" },
  { code: "{{vehicle.purchase_price}}", group: "vehicle", labelKey: "phVehiclePurchasePrice", exampleKey: "exVehiclePurchasePrice" },
  { code: "{{vehicle.sale_price}}", group: "vehicle", labelKey: "phVehicleSalePrice", exampleKey: "exVehicleSalePrice" },
  { code: "{{order.number}}", group: "order", labelKey: "phOrderNumber", exampleKey: "exOrderNumber" },
  { code: "{{order.total_price}}", group: "order", labelKey: "phOrderTotalPrice", exampleKey: "exOrderTotalPrice" },
  { code: "{{order.paid_amount}}", group: "order", labelKey: "phOrderPaidAmount", exampleKey: "exOrderPaidAmount" },
  { code: "{{order.outstanding_balance}}", group: "order", labelKey: "phOrderOutstanding", exampleKey: "exOrderOutstanding" },
  { code: "{{document.generated_date}}", group: "document", labelKey: "phGeneratedDate", exampleKey: "exGeneratedDate" },
  { code: "{{document.generated_city}}", group: "document", labelKey: "phGeneratedCity", exampleKey: "exGeneratedCity" },
  { code: "{{document.signing_date}}", group: "document", labelKey: "phSigningDate", exampleKey: "exSigningDate" },
  { code: "{{document.additional_notes}}", group: "document", labelKey: "phAdditionalNotes", exampleKey: "exAdditionalNotes" },
  { code: "{{employee.full_name}}", group: "employee", labelKey: "phEmployeeFullName", exampleKey: "exEmployeeFullName" },
  { code: "{{deal.number}}", group: "deal", labelKey: "phDealNumber", exampleKey: "exDealNumber" },
  { code: "{{deal.type}}", group: "deal", labelKey: "phDealType", exampleKey: "exDealType" },
  { code: "{{deal.signing_date}}", group: "deal", labelKey: "phDealSigningDate", exampleKey: "exDealSigningDate" },
  { code: "{{deal.signing_place}}", group: "deal", labelKey: "phDealSigningPlace", exampleKey: "exDealSigningPlace" },
  { code: "{{deal.currency}}", group: "deal", labelKey: "phDealCurrency", exampleKey: "exDealCurrency" },
  { code: "{{deal.vehicle_a_value}}", group: "deal", labelKey: "phDealVehicleAValue", exampleKey: "exDealVehicleAValue" },
  { code: "{{deal.vehicle_b_value}}", group: "deal", labelKey: "phDealVehicleBValue", exampleKey: "exDealVehicleBValue" },
  { code: "{{deal.additional_payment}}", group: "deal", labelKey: "phDealAdditionalPayment", exampleKey: "exDealAdditionalPayment" },
  { code: "{{deal.additional_payment_words}}", group: "deal", labelKey: "phDealAdditionalPaymentWords", exampleKey: "exDealAdditionalPaymentWords" },
  { code: "{{deal.additional_payment_payer}}", group: "deal", labelKey: "phDealAdditionalPaymentPayer", exampleKey: "exDealAdditionalPaymentPayer" },
  { code: "{{deal.payment_method}}", group: "deal", labelKey: "phDealPaymentMethod", exampleKey: "exDealPaymentMethod" },
  { code: "{{deal.payment_account}}", group: "deal", labelKey: "phDealPaymentAccount", exampleKey: "exDealPaymentAccount" },
  { code: "{{deal.payment_due_date}}", group: "deal", labelKey: "phDealPaymentDueDate", exampleKey: "exDealPaymentDueDate" },
  { code: "{{deal.payment_status}}", group: "deal", labelKey: "phDealPaymentStatus", exampleKey: "exDealPaymentStatus" },
  { code: "{{deal.vehicle_a_known_defects}}", group: "deal", labelKey: "phDealVehicleADefects", exampleKey: "exDealVehicleADefects" },
  { code: "{{deal.vehicle_b_known_defects}}", group: "deal", labelKey: "phDealVehicleBDefects", exampleKey: "exDealVehicleBDefects" },
  { code: "{{deal.legal_defects_notes}}", group: "deal", labelKey: "phDealLegalDefects", exampleKey: "exDealLegalDefects" },
  { code: "{{deal.service_budget}}", group: "deal", labelKey: "phDealServiceBudget", exampleKey: "exDealServiceBudget" },
  { code: "{{deal.service_budget_formatted}}", group: "deal", labelKey: "phDealServiceBudgetFormatted", exampleKey: "exDealServiceBudgetFormatted" },
  { code: "{{deal.additional_terms}}", group: "deal", labelKey: "phDealAdditionalTerms", exampleKey: "exDealAdditionalTerms" },
  { code: "{{deal.handover_date}}", group: "deal", labelKey: "phDealHandoverDate", exampleKey: "exDealHandoverDate" },
  { code: "{{deal.handover_time}}", group: "deal", labelKey: "phDealHandoverTime", exampleKey: "exDealHandoverTime" },
  { code: "{{deal.handover_place}}", group: "deal", labelKey: "phDealHandoverPlace", exampleKey: "exDealHandoverPlace" },
  { code: "{{deal.handover_notes}}", group: "deal", labelKey: "phDealHandoverNotes", exampleKey: "exDealHandoverNotes" },
  { code: "{{vehicle_a.make}}", group: "vehicle_a", labelKey: "phVehicleAMake", exampleKey: "exVehicleAMake" },
  { code: "{{vehicle_a.model}}", group: "vehicle_a", labelKey: "phVehicleAModel", exampleKey: "exVehicleAModel" },
  { code: "{{vehicle_a.full_name}}", group: "vehicle_a", labelKey: "phVehicleAFullName", exampleKey: "exVehicleAFullName" },
  { code: "{{vehicle_a.vin}}", group: "vehicle_a", labelKey: "phVehicleAVin", exampleKey: "exVehicleAVin" },
  { code: "{{vehicle_a.registration_plate}}", group: "vehicle_a", labelKey: "phVehicleAPlate", exampleKey: "exVehicleAPlate" },
  { code: "{{vehicle_a.first_registration_date}}", group: "vehicle_a", labelKey: "phVehicleAFirstReg", exampleKey: "exVehicleAFirstReg" },
  { code: "{{vehicle_a.mileage}}", group: "vehicle_a", labelKey: "phVehicleAMileage", exampleKey: "exVehicleAMileage" },
  { code: "{{vehicle_a.fuel_type}}", group: "vehicle_a", labelKey: "phVehicleAFuel", exampleKey: "exVehicleAFuel" },
  { code: "{{vehicle_a.engine_capacity}}", group: "vehicle_a", labelKey: "phVehicleAEngine", exampleKey: "exVehicleAEngine" },
  { code: "{{vehicle_a.power_kw}}", group: "vehicle_a", labelKey: "phVehicleAPower", exampleKey: "exVehicleAPower" },
  { code: "{{vehicle_a.color}}", group: "vehicle_a", labelKey: "phVehicleAColor", exampleKey: "exVehicleAColor" },
  { code: "{{vehicle_a.technical_certificate_number}}", group: "vehicle_a", labelKey: "phVehicleATechCert", exampleKey: "exVehicleATechCert" },
  { code: "{{vehicle_a.key_count}}", group: "vehicle_a", labelKey: "phVehicleAKeyCount", exampleKey: "exVehicleAKeyCount" },
  { code: "{{vehicle_a.agreed_value}}", group: "vehicle_a", labelKey: "phVehicleAAgreedValue", exampleKey: "exVehicleAAgreedValue" },
  { code: "{{vehicle_a.make_model}}", group: "vehicle_a", labelKey: "phVehicleAMakeModel", exampleKey: "exVehicleAMakeModel" },
  { code: "{{vehicle_a.registration_number}}", group: "vehicle_a", labelKey: "phVehicleARegistrationNumber", exampleKey: "exVehicleARegistrationNumber" },
  { code: "{{vehicle_a.fuel}}", group: "vehicle_a", labelKey: "phVehicleAFuelShort", exampleKey: "exVehicleAFuelShort" },
  { code: "{{vehicle_a.engine_volume}}", group: "vehicle_a", labelKey: "phVehicleAEngineVolume", exampleKey: "exVehicleAEngineVolume" },
  { code: "{{vehicle_a.engine_power}}", group: "vehicle_a", labelKey: "phVehicleAEnginePower", exampleKey: "exVehicleAEnginePower" },
  { code: "{{vehicle_a.technical_document_number}}", group: "vehicle_a", labelKey: "phVehicleATechDocumentNumber", exampleKey: "exVehicleATechDocumentNumber" },
  { code: "{{vehicle_a.agreed_value_formatted}}", group: "vehicle_a", labelKey: "phVehicleAAgreedValueFormatted", exampleKey: "exVehicleAAgreedValueFormatted" },
  { code: "{{vehicle_a.known_defects}}", group: "vehicle_a", labelKey: "phVehicleAKnownDefects", exampleKey: "exVehicleAKnownDefects" },
  { code: "{{vehicle_a.fuel_engine_power}}", group: "vehicle_a", labelKey: "phVehicleAFuelEnginePower", exampleKey: "exVehicleAFuelEnginePower" },
  { code: "{{vehicle_b.make}}", group: "vehicle_b", labelKey: "phVehicleBMake", exampleKey: "exVehicleBMake" },
  { code: "{{vehicle_b.model}}", group: "vehicle_b", labelKey: "phVehicleBModel", exampleKey: "exVehicleBModel" },
  { code: "{{vehicle_b.full_name}}", group: "vehicle_b", labelKey: "phVehicleBFullName", exampleKey: "exVehicleBFullName" },
  { code: "{{vehicle_b.vin}}", group: "vehicle_b", labelKey: "phVehicleBVin", exampleKey: "exVehicleBVin" },
  { code: "{{vehicle_b.registration_plate}}", group: "vehicle_b", labelKey: "phVehicleBPlate", exampleKey: "exVehicleBPlate" },
  { code: "{{vehicle_b.first_registration_date}}", group: "vehicle_b", labelKey: "phVehicleBFirstReg", exampleKey: "exVehicleBFirstReg" },
  { code: "{{vehicle_b.mileage}}", group: "vehicle_b", labelKey: "phVehicleBMileage", exampleKey: "exVehicleBMileage" },
  { code: "{{vehicle_b.fuel_type}}", group: "vehicle_b", labelKey: "phVehicleBFuel", exampleKey: "exVehicleBFuel" },
  { code: "{{vehicle_b.engine_capacity}}", group: "vehicle_b", labelKey: "phVehicleBEngine", exampleKey: "exVehicleBEngine" },
  { code: "{{vehicle_b.power_kw}}", group: "vehicle_b", labelKey: "phVehicleBPower", exampleKey: "exVehicleBPower" },
  { code: "{{vehicle_b.color}}", group: "vehicle_b", labelKey: "phVehicleBColor", exampleKey: "exVehicleBColor" },
  { code: "{{vehicle_b.technical_certificate_number}}", group: "vehicle_b", labelKey: "phVehicleBTechCert", exampleKey: "exVehicleBTechCert" },
  { code: "{{vehicle_b.key_count}}", group: "vehicle_b", labelKey: "phVehicleBKeyCount", exampleKey: "exVehicleBKeyCount" },
  { code: "{{vehicle_b.agreed_value}}", group: "vehicle_b", labelKey: "phVehicleBAgreedValue", exampleKey: "exVehicleBAgreedValue" },
  { code: "{{vehicle_b.make_model}}", group: "vehicle_b", labelKey: "phVehicleBMakeModel", exampleKey: "exVehicleBMakeModel" },
  { code: "{{vehicle_b.registration_number}}", group: "vehicle_b", labelKey: "phVehicleBRegistrationNumber", exampleKey: "exVehicleBRegistrationNumber" },
  { code: "{{vehicle_b.fuel}}", group: "vehicle_b", labelKey: "phVehicleBFuelShort", exampleKey: "exVehicleBFuelShort" },
  { code: "{{vehicle_b.engine_volume}}", group: "vehicle_b", labelKey: "phVehicleBEngineVolume", exampleKey: "exVehicleBEngineVolume" },
  { code: "{{vehicle_b.engine_power}}", group: "vehicle_b", labelKey: "phVehicleBEnginePower", exampleKey: "exVehicleBEnginePower" },
  { code: "{{vehicle_b.technical_document_number}}", group: "vehicle_b", labelKey: "phVehicleBTechDocumentNumber", exampleKey: "exVehicleBTechDocumentNumber" },
  { code: "{{vehicle_b.agreed_value_formatted}}", group: "vehicle_b", labelKey: "phVehicleBAgreedValueFormatted", exampleKey: "exVehicleBAgreedValueFormatted" },
  { code: "{{vehicle_b.known_defects}}", group: "vehicle_b", labelKey: "phVehicleBKnownDefects", exampleKey: "exVehicleBKnownDefects" },
  { code: "{{vehicle_b.fuel_engine_power}}", group: "vehicle_b", labelKey: "phVehicleBFuelEnginePower", exampleKey: "exVehicleBFuelEnginePower" },
  { code: "{{payment.amount_formatted}}", group: "payment", labelKey: "phPaymentAmountFormatted", exampleKey: "exPaymentAmountFormatted" },
  { code: "{{payment.amount_in_words}}", group: "payment", labelKey: "phPaymentAmountInWords", exampleKey: "exPaymentAmountInWords" },
  { code: "{{payment.payer_customer_checkbox}}", group: "payment", labelKey: "phPaymentPayerCustomerCheckbox", exampleKey: "exPaymentPayerCustomerCheckbox" },
  { code: "{{payment.payer_remauto_checkbox}}", group: "payment", labelKey: "phPaymentPayerRemautoCheckbox", exampleKey: "exPaymentPayerRemautoCheckbox" },
  { code: "{{payment.cash_checkbox}}", group: "payment", labelKey: "phPaymentCashCheckbox", exampleKey: "exPaymentCashCheckbox" },
  { code: "{{payment.bank_transfer_checkbox}}", group: "payment", labelKey: "phPaymentBankTransferCheckbox", exampleKey: "exPaymentBankTransferCheckbox" },
  { code: "{{payment.other_checkbox}}", group: "payment", labelKey: "phPaymentOtherCheckbox", exampleKey: "exPaymentOtherCheckbox" },
  { code: "{{payment.bank_account}}", group: "payment", labelKey: "phPaymentBankAccount", exampleKey: "exPaymentBankAccount" },
  { code: "{{payment.due_date}}", group: "payment", labelKey: "phPaymentDueDate", exampleKey: "exPaymentDueDate" },
  { code: "{{payment.other_text}}", group: "payment", labelKey: "phPaymentOtherText", exampleKey: "exPaymentOtherText" },
  { code: "{{payment.other_method}}", group: "payment", labelKey: "phPaymentOtherMethod", exampleKey: "exPaymentOtherMethod" },
  { code: "{{registration.each_party_checkbox}}", group: "registration", labelKey: "phRegistrationEachPartyCheckbox", exampleKey: "exRegistrationEachPartyCheckbox" },
  { code: "{{registration.remauto_checkbox}}", group: "registration", labelKey: "phRegistrationRemautoCheckbox", exampleKey: "exRegistrationRemautoCheckbox" },
  { code: "{{registration.customer_checkbox}}", group: "registration", labelKey: "phRegistrationCustomerCheckbox", exampleKey: "exRegistrationCustomerCheckbox" },
  { code: "{{registration.other_checkbox}}", group: "registration", labelKey: "phRegistrationOtherCheckbox", exampleKey: "exRegistrationOtherCheckbox" },
  { code: "{{registration.other_text}}", group: "registration", labelKey: "phRegistrationOtherText", exampleKey: "exRegistrationOtherText" },
  { code: "{{service.approved_budget_formatted}}", group: "service", labelKey: "phServiceApprovedBudgetFormatted", exampleKey: "exServiceApprovedBudgetFormatted" },
  { code: "{{handover.vehicle_a.datetime}}", group: "handover", labelKey: "phHandoverADatetime", exampleKey: "exHandoverADatetime" },
  { code: "{{handover.vehicle_a.mileage}}", group: "handover", labelKey: "phHandoverAMileage", exampleKey: "exHandoverAMileage" },
  { code: "{{handover.vehicle_a.fuel_level}}", group: "handover", labelKey: "phHandoverAFuel", exampleKey: "exHandoverAFuel" },
  { code: "{{handover.vehicle_a.key_count}}", group: "handover", labelKey: "phHandoverAKeyCount", exampleKey: "exHandoverAKeyCount" },
  { code: "{{handover.vehicle_a.documents}}", group: "handover", labelKey: "phHandoverADocuments", exampleKey: "exHandoverADocuments" },
  { code: "{{handover.vehicle_a.documents_checkboxes}}", group: "handover", labelKey: "phHandoverADocumentsCheckboxes", exampleKey: "exHandoverADocumentsCheckboxes" },
  { code: "{{handover.vehicle_a.accessories}}", group: "handover", labelKey: "phHandoverAAccessories", exampleKey: "exHandoverAAccessories" },
  { code: "{{handover.vehicle_a.visible_damage}}", group: "handover", labelKey: "phHandoverADamage", exampleKey: "exHandoverADamage" },
  { code: "{{handover.vehicle_b.datetime}}", group: "handover", labelKey: "phHandoverBDatetime", exampleKey: "exHandoverBDatetime" },
  { code: "{{handover.vehicle_b.mileage}}", group: "handover", labelKey: "phHandoverBMileage", exampleKey: "exHandoverBMileage" },
  { code: "{{handover.vehicle_b.fuel_level}}", group: "handover", labelKey: "phHandoverBFuel", exampleKey: "exHandoverBFuel" },
  { code: "{{handover.vehicle_b.key_count}}", group: "handover", labelKey: "phHandoverBKeyCount", exampleKey: "exHandoverBKeyCount" },
  { code: "{{handover.vehicle_b.documents}}", group: "handover", labelKey: "phHandoverBDocuments", exampleKey: "exHandoverBDocuments" },
  { code: "{{handover.vehicle_b.documents_checkboxes}}", group: "handover", labelKey: "phHandoverBDocumentsCheckboxes", exampleKey: "exHandoverBDocumentsCheckboxes" },
  { code: "{{handover.delivery_date}}", group: "handover", labelKey: "phHandoverDeliveryDate", exampleKey: "exHandoverDeliveryDate" },
  { code: "{{handover.date}}", group: "handover", labelKey: "phHandoverDate", exampleKey: "exHandoverDate" },
  { code: "{{handover.delivery_place}}", group: "handover", labelKey: "phHandoverDeliveryPlace", exampleKey: "exHandoverDeliveryPlace" },
  { code: "{{handover.place}}", group: "handover", labelKey: "phHandoverPlace", exampleKey: "exHandoverPlace" },
  { code: "{{handover.deliverer_name}}", group: "handover", labelKey: "phHandoverDelivererName", exampleKey: "exHandoverDelivererName" },
  { code: "{{handover.receiver_name}}", group: "handover", labelKey: "phHandoverReceiverName", exampleKey: "exHandoverReceiverName" },
  { code: "{{handover.vehicle_b.accessories}}", group: "handover", labelKey: "phHandoverBAccessories", exampleKey: "exHandoverBAccessories" },
  { code: "{{handover.vehicle_b.visible_damage}}", group: "handover", labelKey: "phHandoverBDamage", exampleKey: "exHandoverBDamage" },
  { code: "{{handover.notes}}", group: "handover", labelKey: "phHandoverNotes", exampleKey: "exHandoverNotes" },
  { code: "{{handover.notes_continued}}", group: "handover", labelKey: "phHandoverNotesContinued", exampleKey: "exHandoverNotesContinued" },
  { code: "{{power_of_attorney.principal.type}}", group: "power_of_attorney", labelKey: "phPoaPrincipalType", exampleKey: "exPoaPrincipalType" },
  { code: "{{power_of_attorney.principal.full_name}}", group: "power_of_attorney", labelKey: "phPoaPrincipalFullName", exampleKey: "exPoaPrincipalFullName" },
  { code: "{{power_of_attorney.principal.company_name}}", group: "power_of_attorney", labelKey: "phPoaPrincipalCompanyName", exampleKey: "exPoaPrincipalCompanyName" },
  { code: "{{power_of_attorney.principal.birth_date}}", group: "power_of_attorney", labelKey: "phPoaPrincipalBirthDate", exampleKey: "exPoaPrincipalBirthDate" },
  { code: "{{power_of_attorney.principal.personal_id_number}}", group: "power_of_attorney", labelKey: "phPoaPrincipalPersonalId", exampleKey: "exPoaPrincipalPersonalId" },
  { code: "{{power_of_attorney.principal.identity_document_number}}", group: "power_of_attorney", labelKey: "phPoaPrincipalIdentityDoc", exampleKey: "exPoaPrincipalIdentityDoc" },
  { code: "{{power_of_attorney.principal.ico}}", group: "power_of_attorney", labelKey: "phPoaPrincipalIco", exampleKey: "exPoaPrincipalIco" },
  { code: "{{power_of_attorney.principal.dic}}", group: "power_of_attorney", labelKey: "phPoaPrincipalDic", exampleKey: "exPoaPrincipalDic" },
  { code: "{{power_of_attorney.principal.address}}", group: "power_of_attorney", labelKey: "phPoaPrincipalAddress", exampleKey: "exPoaPrincipalAddress" },
  { code: "{{power_of_attorney.principal.represented_by}}", group: "power_of_attorney", labelKey: "phPoaPrincipalRepresentedBy", exampleKey: "exPoaPrincipalRepresentedBy" },
  { code: "{{power_of_attorney.principal.representative_position}}", group: "power_of_attorney", labelKey: "phPoaPrincipalRepPosition", exampleKey: "exPoaPrincipalRepPosition" },
  { code: "{{power_of_attorney.principal.phone}}", group: "power_of_attorney", labelKey: "phPoaPrincipalPhone", exampleKey: "exPoaPrincipalPhone" },
  { code: "{{power_of_attorney.principal.email}}", group: "power_of_attorney", labelKey: "phPoaPrincipalEmail", exampleKey: "exPoaPrincipalEmail" },
  { code: "{{power_of_attorney.authorized_person.type}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedType", exampleKey: "exPoaAuthorizedType" },
  { code: "{{power_of_attorney.authorized_person.full_name}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedFullName", exampleKey: "exPoaAuthorizedFullName" },
  { code: "{{power_of_attorney.authorized_person.company_name}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedCompanyName", exampleKey: "exPoaAuthorizedCompanyName" },
  { code: "{{power_of_attorney.authorized_person.birth_date}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedBirthDate", exampleKey: "exPoaAuthorizedBirthDate" },
  { code: "{{power_of_attorney.authorized_person.personal_id_number}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedPersonalId", exampleKey: "exPoaAuthorizedPersonalId" },
  { code: "{{power_of_attorney.authorized_person.identity_document_number}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedIdentityDoc", exampleKey: "exPoaAuthorizedIdentityDoc" },
  { code: "{{power_of_attorney.authorized_person.ico}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedIco", exampleKey: "exPoaAuthorizedIco" },
  { code: "{{power_of_attorney.authorized_person.dic}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedDic", exampleKey: "exPoaAuthorizedDic" },
  { code: "{{power_of_attorney.authorized_person.address}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedAddress", exampleKey: "exPoaAuthorizedAddress" },
  { code: "{{power_of_attorney.authorized_person.represented_by}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedRepresentedBy", exampleKey: "exPoaAuthorizedRepresentedBy" },
  { code: "{{power_of_attorney.authorized_person.representative_position}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedRepPosition", exampleKey: "exPoaAuthorizedRepPosition" },
  { code: "{{power_of_attorney.authorized_person.phone}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedPhone", exampleKey: "exPoaAuthorizedPhone" },
  { code: "{{power_of_attorney.authorized_person.email}}", group: "power_of_attorney", labelKey: "phPoaAuthorizedEmail", exampleKey: "exPoaAuthorizedEmail" },
  { code: "{{power_of_attorney.vehicle.make}}", group: "power_of_attorney", labelKey: "phPoaVehicleMake", exampleKey: "exPoaVehicleMake" },
  { code: "{{power_of_attorney.vehicle.model}}", group: "power_of_attorney", labelKey: "phPoaVehicleModel", exampleKey: "exPoaVehicleModel" },
  { code: "{{power_of_attorney.vehicle.full_name}}", group: "power_of_attorney", labelKey: "phPoaVehicleFullName", exampleKey: "exPoaVehicleFullName" },
  { code: "{{power_of_attorney.vehicle.vin}}", group: "power_of_attorney", labelKey: "phPoaVehicleVin", exampleKey: "exPoaVehicleVin" },
  { code: "{{power_of_attorney.vehicle.registration_plate}}", group: "power_of_attorney", labelKey: "phPoaVehiclePlate", exampleKey: "exPoaVehiclePlate" },
  { code: "{{power_of_attorney.vehicle.first_registration_date}}", group: "power_of_attorney", labelKey: "phPoaVehicleFirstReg", exampleKey: "exPoaVehicleFirstReg" },
  { code: "{{power_of_attorney.vehicle.technical_certificate_number}}", group: "power_of_attorney", labelKey: "phPoaVehicleTechCert", exampleKey: "exPoaVehicleTechCert" },
  { code: "{{power_of_attorney.vehicle.color}}", group: "power_of_attorney", labelKey: "phPoaVehicleColor", exampleKey: "exPoaVehicleColor" },
  { code: "{{power_of_attorney.vehicle.mileage}}", group: "power_of_attorney", labelKey: "phPoaVehicleMileage", exampleKey: "exPoaVehicleMileage" },
  { code: "{{power_of_attorney.vehicle.fuel_type}}", group: "power_of_attorney", labelKey: "phPoaVehicleFuel", exampleKey: "exPoaVehicleFuel" },
  { code: "{{power_of_attorney.vehicle.engine_capacity}}", group: "power_of_attorney", labelKey: "phPoaVehicleEngine", exampleKey: "exPoaVehicleEngine" },
  { code: "{{power_of_attorney.vehicle.power_kw}}", group: "power_of_attorney", labelKey: "phPoaVehiclePower", exampleKey: "exPoaVehiclePower" },
  { code: "{{power_of_attorney.vehicle.registered_owner_name}}", group: "power_of_attorney", labelKey: "phPoaVehicleOwnerName", exampleKey: "exPoaVehicleOwnerName" },
  { code: "{{power_of_attorney.vehicle.registered_owner_address}}", group: "power_of_attorney", labelKey: "phPoaVehicleOwnerAddress", exampleKey: "exPoaVehicleOwnerAddress" },
  { code: "{{power_of_attorney.vehicle.registered_owner_identification}}", group: "power_of_attorney", labelKey: "phPoaVehicleOwnerId", exampleKey: "exPoaVehicleOwnerId" },
  { code: "{{power_of_attorney.vehicle.registration_country}}", group: "power_of_attorney", labelKey: "phPoaVehicleRegCountry", exampleKey: "exPoaVehicleRegCountry" },
  { code: "{{power_of_attorney.authorization.scope_text}}", group: "power_of_attorney", labelKey: "phPoaAuthScopeText", exampleKey: "exPoaAuthScopeText" },
  { code: "{{power_of_attorney.authorization.additional_text}}", group: "power_of_attorney", labelKey: "phPoaAuthAdditional", exampleKey: "exPoaAuthAdditional" },
  { code: "{{power_of_attorney.signing.place}}", group: "power_of_attorney", labelKey: "phPoaSigningPlace", exampleKey: "exPoaSigningPlace" },
  { code: "{{power_of_attorney.signing.date}}", group: "power_of_attorney", labelKey: "phPoaSigningDate", exampleKey: "exPoaSigningDate" },
  { code: "{{power_of_attorney.validity.type}}", group: "power_of_attorney", labelKey: "phPoaValidityType", exampleKey: "exPoaValidityType" },
  { code: "{{power_of_attorney.validity.valid_from}}", group: "power_of_attorney", labelKey: "phPoaValidFrom", exampleKey: "exPoaValidFrom" },
  { code: "{{power_of_attorney.validity.valid_until}}", group: "power_of_attorney", labelKey: "phPoaValidUntil", exampleKey: "exPoaValidUntil" },
  { code: "{{power_of_attorney.validity.notarized_signature}}", group: "power_of_attorney", labelKey: "phPoaNotarized", exampleKey: "exPoaNotarized" },
  { code: "{{power_of_attorney.validity.original_count}}", group: "power_of_attorney", labelKey: "phPoaOriginalCount", exampleKey: "exPoaOriginalCount" },
  { code: "{{power_of_attorney.additional_notes}}", group: "power_of_attorney", labelKey: "phPoaAdditionalNotes", exampleKey: "exPoaAdditionalNotes" },
];

export const KNOWN_PLACEHOLDER_CODES = new Set(
  DOCUMENT_TEMPLATE_PLACEHOLDERS.map((item) => item.code)
);

export const PLACEHOLDER_GROUPS = [
  "company",
  "client",
  "customer",
  "vehicle",
  "order",
  "employee",
  "document",
  "deal",
  "vehicle_a",
  "vehicle_b",
  "payment",
  "registration",
  "service",
  "handover",
  "power_of_attorney",
] as const;

export function classifyPlaceholders(codes: string[]) {
  const recognized: string[] = [];
  const unknown: string[] = [];

  for (const code of codes) {
    if (isKnownPlaceholderCode(code, KNOWN_PLACEHOLDER_CODES)) {
      recognized.push(code);
    } else {
      unknown.push(code);
    }
  }

  return { recognized, unknown };
}

export function getSampleTemplateData(): import("@/lib/types/document-templates").DocumentTemplateData {
  return {
    company: {
      name: "RemAuto s.r.o.",
      ico: "12345678",
      dic: "CZ12345678",
      address: "Hlavní 1",
      city: "Praha",
      phone: "+420 123 456 789",
      email: "info@remauto.cz",
    },
    client: {
      full_name: "Jan Novák",
      company_name: "Novák s.r.o.",
      birth_date: "",
      id_number: "",
      address: "Dlouhá 10, Praha",
      phone: "+420 777 000 111",
      email: "jan@example.cz",
    },
    vehicle: {
      make: "BMW",
      model: "530d",
      year: "2019",
      vin: "WBA12345678900000",
      plate: "1AB2345",
      mileage: "",
      purchase_price: "450 000 Kč",
      sale_price: "520 000 Kč",
    },
    order: {
      number: "1042",
      total_price: "12 500 Kč",
      paid_amount: "5 000 Kč",
      outstanding_balance: "7 500 Kč",
    },
    document: {
      generated_date: "27.07.2026",
      generated_city: "Praha",
      signing_date: "27.07.2026",
      additional_notes: "",
    },
    employee: {
      full_name: "Petr Manager",
    },
  };
}
